### ISSUE TITLE
你好，关于收录请求

### ISSUE THREAD

**Issue by ShuJuLiu2001** [233boy/ao3#1]
你好，我目前正在尝试做一个镜像的整合页，请问我可以收录你的镜像网址吗？🎈

**Comment by 233boy** [comment]
@ShuJuLiu2001 
那显然是可以的 :)

**Comment by VincentVictorMi** [comment]
好的，多谢ヾ(≧▽≦*)o

**Comment by ShuJuLiu2001** [comment]
好的，多谢ヾ(≧▽≦*)o

**Comment by ShuJuLiu2001** [comment]
网址已收录在 https://github.com/shujuliu/AO3-Mirror-Site 
再次表示感谢(*^▽^*)
